/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RenovationRouteImport } from './routes/renovation'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as NosProjetsRouteImport } from './routes/nos-projets'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DepannageRouteImport } from './routes/depannage'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarrieresRouteImport } from './routes/carrieres'
import { Route as ActualiteRouteImport } from './routes/actualite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NosProjetsProjectIdRouteImport } from './routes/nos-projets.$projectId'
import { Route as AdminProjetsRouteImport } from './routes/admin/projets'
import { Route as ApiPublicHooksScrapeArticlesRouteImport } from './routes/api/public/hooks/scrape-articles'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RenovationRoute = RenovationRouteImport.update({
  id: '/renovation',
  path: '/renovation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const NosProjetsRoute = NosProjetsRouteImport.update({
  id: '/nos-projets',
  path: '/nos-projets',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DepannageRoute = DepannageRouteImport.update({
  id: '/depannage',
  path: '/depannage',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrieresRoute = CarrieresRouteImport.update({
  id: '/carrieres',
  path: '/carrieres',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualiteRoute = ActualiteRouteImport.update({
  id: '/actualite',
  path: '/actualite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NosProjetsProjectIdRoute = NosProjetsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => NosProjetsRoute,
} as any)
const AdminProjetsRoute = AdminProjetsRouteImport.update({
  id: '/admin/projets',
  path: '/admin/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScrapeArticlesRoute =
  ApiPublicHooksScrapeArticlesRouteImport.update({
    id: '/api/public/hooks/scrape-articles',
    path: '/api/public/hooks/scrape-articles',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualite': typeof ActualiteRoute
  '/carrieres': typeof CarrieresRoute
  '/contact': typeof ContactRoute
  '/depannage': typeof DepannageRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/nos-projets': typeof NosProjetsRouteWithChildren
  '/presentation': typeof PresentationRoute
  '/privacy': typeof PrivacyRoute
  '/projets': typeof ProjetsRoute
  '/renovation': typeof RenovationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/projets': typeof AdminProjetsRoute
  '/nos-projets/$projectId': typeof NosProjetsProjectIdRoute
  '/api/public/hooks/scrape-articles': typeof ApiPublicHooksScrapeArticlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualite': typeof ActualiteRoute
  '/carrieres': typeof CarrieresRoute
  '/contact': typeof ContactRoute
  '/depannage': typeof DepannageRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/nos-projets': typeof NosProjetsRouteWithChildren
  '/presentation': typeof PresentationRoute
  '/privacy': typeof PrivacyRoute
  '/projets': typeof ProjetsRoute
  '/renovation': typeof RenovationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/projets': typeof AdminProjetsRoute
  '/nos-projets/$projectId': typeof NosProjetsProjectIdRoute
  '/api/public/hooks/scrape-articles': typeof ApiPublicHooksScrapeArticlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualite': typeof ActualiteRoute
  '/carrieres': typeof CarrieresRoute
  '/contact': typeof ContactRoute
  '/depannage': typeof DepannageRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/nos-projets': typeof NosProjetsRouteWithChildren
  '/presentation': typeof PresentationRoute
  '/privacy': typeof PrivacyRoute
  '/projets': typeof ProjetsRoute
  '/renovation': typeof RenovationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/projets': typeof AdminProjetsRoute
  '/nos-projets/$projectId': typeof NosProjetsProjectIdRoute
  '/api/public/hooks/scrape-articles': typeof ApiPublicHooksScrapeArticlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualite'
    | '/carrieres'
    | '/contact'
    | '/depannage'
    | '/documents'
    | '/login'
    | '/mentions-legales'
    | '/nos-projets'
    | '/presentation'
    | '/privacy'
    | '/projets'
    | '/renovation'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/admin/projets'
    | '/nos-projets/$projectId'
    | '/api/public/hooks/scrape-articles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualite'
    | '/carrieres'
    | '/contact'
    | '/depannage'
    | '/documents'
    | '/login'
    | '/mentions-legales'
    | '/nos-projets'
    | '/presentation'
    | '/privacy'
    | '/projets'
    | '/renovation'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/admin/projets'
    | '/nos-projets/$projectId'
    | '/api/public/hooks/scrape-articles'
  id:
    | '__root__'
    | '/'
    | '/actualite'
    | '/carrieres'
    | '/contact'
    | '/depannage'
    | '/documents'
    | '/login'
    | '/mentions-legales'
    | '/nos-projets'
    | '/presentation'
    | '/privacy'
    | '/projets'
    | '/renovation'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/admin/projets'
    | '/nos-projets/$projectId'
    | '/api/public/hooks/scrape-articles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualiteRoute: typeof ActualiteRoute
  CarrieresRoute: typeof CarrieresRoute
  ContactRoute: typeof ContactRoute
  DepannageRoute: typeof DepannageRoute
  DocumentsRoute: typeof DocumentsRoute
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  NosProjetsRoute: typeof NosProjetsRouteWithChildren
  PresentationRoute: typeof PresentationRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjetsRoute: typeof ProjetsRoute
  RenovationRoute: typeof RenovationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminProjetsRoute: typeof AdminProjetsRoute
  ApiPublicHooksScrapeArticlesRoute: typeof ApiPublicHooksScrapeArticlesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovation': {
      id: '/renovation'
      path: '/renovation'
      fullPath: '/renovation'
      preLoaderRoute: typeof RenovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nos-projets': {
      id: '/nos-projets'
      path: '/nos-projets'
      fullPath: '/nos-projets'
      preLoaderRoute: typeof NosProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depannage': {
      id: '/depannage'
      path: '/depannage'
      fullPath: '/depannage'
      preLoaderRoute: typeof DepannageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrieres': {
      id: '/carrieres'
      path: '/carrieres'
      fullPath: '/carrieres'
      preLoaderRoute: typeof CarrieresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualite': {
      id: '/actualite'
      path: '/actualite'
      fullPath: '/actualite'
      preLoaderRoute: typeof ActualiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nos-projets/$projectId': {
      id: '/nos-projets/$projectId'
      path: '/$projectId'
      fullPath: '/nos-projets/$projectId'
      preLoaderRoute: typeof NosProjetsProjectIdRouteImport
      parentRoute: typeof NosProjetsRoute
    }
    '/admin/projets': {
      id: '/admin/projets'
      path: '/admin/projets'
      fullPath: '/admin/projets'
      preLoaderRoute: typeof AdminProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scrape-articles': {
      id: '/api/public/hooks/scrape-articles'
      path: '/api/public/hooks/scrape-articles'
      fullPath: '/api/public/hooks/scrape-articles'
      preLoaderRoute: typeof ApiPublicHooksScrapeArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NosProjetsRouteChildren {
  NosProjetsProjectIdRoute: typeof NosProjetsProjectIdRoute
}

const NosProjetsRouteChildren: NosProjetsRouteChildren = {
  NosProjetsProjectIdRoute: NosProjetsProjectIdRoute,
}

const NosProjetsRouteWithChildren = NosProjetsRoute._addFileChildren(
  NosProjetsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualiteRoute: ActualiteRoute,
  CarrieresRoute: CarrieresRoute,
  ContactRoute: ContactRoute,
  DepannageRoute: DepannageRoute,
  DocumentsRoute: DocumentsRoute,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  NosProjetsRoute: NosProjetsRouteWithChildren,
  PresentationRoute: PresentationRoute,
  PrivacyRoute: PrivacyRoute,
  ProjetsRoute: ProjetsRoute,
  RenovationRoute: RenovationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminProjetsRoute: AdminProjetsRoute,
  ApiPublicHooksScrapeArticlesRoute: ApiPublicHooksScrapeArticlesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
