
UPDATE projects SET title='Rénovation appartement Champel', category='Rénovation', description='Réfection complète de l''installation électrique d''un appartement à Champel : tableau, prises, éclairage et mise aux normes.' WHERE instagram_url='https://www.instagram.com/p/DW3-Q-WDI3O/';
UPDATE projects SET title='Éclairage architectural sur mesure', category='Éclairage', description='Étude et mise en lumière d''espaces de vie avec un éclairage LED architectural sur mesure.' WHERE instagram_url='https://www.instagram.com/p/DW3972xDOvB/';
UPDATE projects SET title='Système de sécurité résidentiel', category='Sécurité', description='Installation d''un système d''alarme et de vidéosurveillance pour une villa privée.' WHERE instagram_url='https://www.instagram.com/p/DN0Tbv_WOgw/';
UPDATE projects SET title='Bureaux d''entreprise à Genève', category='Commercial', description='Câblage informatique, éclairage et tableaux pour un nouvel espace de bureaux.' WHERE instagram_url='https://www.instagram.com/p/DNpdVSAs6wW/';
UPDATE projects SET title='Villa contemporaine — installation complète', category='Grands projets', description='Installation électrique complète d''une villa contemporaine : domotique, éclairage, sécurité.' WHERE instagram_url='https://www.instagram.com/p/DJb0ts5o4dM/';
UPDATE projects SET title='Mise aux normes d''un immeuble', category='Rénovation', description='Mise aux normes complète de l''installation électrique d''un immeuble locatif genevois.' WHERE instagram_url='https://www.instagram.com/p/DJMGNtFoM0A/';
UPDATE projects SET title='Éclairage de boutique', category='Commercial', description='Mise en lumière soignée d''une boutique au cœur de Genève.' WHERE instagram_url='https://www.instagram.com/p/DI1UE4ksOot/';
UPDATE projects SET title='Tableau électrique haute performance', category='Résidentiel', description='Remplacement et modernisation d''un tableau électrique pour une habitation privée.' WHERE instagram_url='https://www.instagram.com/p/DFch92ksYWt/';
UPDATE projects SET title='Vidéosurveillance professionnelle', category='Sécurité', description='Installation d''un système de vidéosurveillance pour un site professionnel.' WHERE instagram_url='https://www.instagram.com/p/DFZ94DMMMES/';
UPDATE projects SET title='Éclairage extérieur paysager', category='Éclairage', description='Mise en valeur d''un jardin et d''une façade par un éclairage extérieur LED.' WHERE instagram_url='https://www.instagram.com/p/DFXWxfoMnRg/';
UPDATE projects SET title='Chantier d''envergure — bâtiment neuf', category='Grands projets', description='Installation électrique complète d''un bâtiment neuf, du tableau général aux finitions.' WHERE instagram_url='https://www.instagram.com/p/DFPs1GMs-C6/';
